[package]
name = "elf64"
version = "0.1.0"
edition = "2021"

[dependencies]
enumflags2 = { version = "0.7.10", features = ["serde"] }
nom = "7.1.3"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
